---
title: "HW 1"
author: "Mateo Forero"
output: html_document
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file, encoding = encoding,
  output_file = file.path(dirname(input_file), out_dir, 'index.html'))})
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
# Using wage data set from the ISLR package
library(ISLR)
library(tidyverse)
library(viridis)

filtered_data <- Wage %>%
  group_by(race, education) %>%
  summarise(avg_wage = mean(wage))

filtered_data$race <- str_sub(filtered_data$race,4)

w_plot <- ggplot(data = filtered_data, aes(x = education,
                                           y = avg_wage, fill = race))+ 
  geom_bar(stat = 'identity', color = 'black', position=position_dodge(),
           width = 0.6)+
  theme_minimal(base_size = 12) +
  ylab("Average Wage [$K]") + xlab("Education")+ 
  scale_y_continuous(labels = scales::dollar_format()) +
  ggtitle("Average Wage in the Mid-Atlanic by Race and Education") +
  guides(fill=guide_legend(title="Race"))
pdf("HW_1_Plot.pdf", height=4, width=8)
```

```{r, fig.width=8,fig.height=4}
print(w_plot)
```

